### ISSUE TITLE
what is the calculation time of OPGP

### ISSUE THREAD

**Issue by teddyluo** [georgeliu233/OPGP#1]
Hi, I roughly read the whole paper and want to know two details: 
1)  on what kind of hardware was this method tested?
2）what is the computation time of OPGP (training? and inference?)?

Can you provide more details about OPGP? many thanks

**Comment by georgeliu233** [comment]
> Hi, I roughly read the whole paper and want to know two details:
> 
> 1. on what kind of hardware was this method tested?
>    2）what is the computation time of OPGP (training? and inference?)?
> 
> Can you provide more details about OPGP? many thanks

Hi Teddy, thank you for your interest of our work :)
For your questions:
For Q1: 1) We conducted open-loop testing for planning and testing for prediction on log-replayed random-splited WOMD (validation) data, and we did not conduct HIL (hardware in loop) test; 2) Currently we train and test for our result on the same GPU configs (on 4 A100 40G) 
For Q2:  cumputational time is about 0.03s for training and about 0.15-0.2s for testing (planning+refinement) per sample;

I plan to provide more of the related information after this year's WOMD challenge
