### ISSUE TITLE
第一阶段的L_plan那一块GT是怎么生成的

### ISSUE THREAD

**Issue by Gxhappiness** [georgeliu233/OPGP#3]
第一阶段的L_plan那一块，GT是怎么生成的，k个GT还有p_k是哪来的

**Comment by georgeliu233** [comment]
Hi,
stage 1 的plan直接从Waymo的sdc vehicle给出gt；
p_k代表了对于plan的confidence，网络有一个打分器输出，它的gt是动态的，根据输出k条plan中和gt最相似的p=1其他p=0.

**Comment by Gxhappiness** [comment]
> 

非常感谢，可以麻烦再问一下第一阶段规划头那一块，k个锚点具体指的是？

**Comment by georgeliu233** [comment]
Hi!
Anchors 引导了k个 planning query的初始化，我们这里遵循multipath++进行了随机初始化作为输入，也可以尝试遵循如multipath或MTR方式用K-means得到k个cluster，作为更直观的引导

**Comment by Gxhappiness** [comment]
> Hi! Anchors 引导了k个 planning query的初始化，我们这里遵循multipath++进行了随机初始化作为输入，也可以尝试遵循如multipath或MTR方式用K-means得到k个cluster，作为更直观的引导

谢谢解答，非常精彩的工作！
