### ISSUE TITLE
There is no generate_target_course function in plan_utils.py

### ISSUE THREAD

**Issue by soyaCat** [georgeliu233/OPGP#4]
Hi
I want to run your propocess.py python file but. I can't do it
In your 'preprocess.py', it tries to import all functions from 'utils.train_utils.py'. However, 'utils.train_utils.py' attempts to call 'generate_target_course' function which is not defined in 'utils.plan_utils.py'. As a result, it seems that 'preprocess.py' does not work. Can you make a correction on this?

**Comment by ZikangXiong** [comment]
Same issue here. `generate_target_course` is missing.

**Comment by WeiXiCZ** [comment]
+1😢

**Comment by georgeliu233** [comment]
Extremely sorry for the inconvenience!

I added the ```generate_target_course``` function.

If you have any questions, don't hesitate to reach me!

**Comment by ZikangXiong** [comment]
Thanks for the reply and fixing the issue! 

A quick note on running
```
python preprocess.py \
--root_dir path/to/your/Waymo_Dataset/scenario/ \
--save_dir path/to/your/processed_data/ \
--processes=16
```

Under the path/to/your/processed_data/, we should create two sub-folders named
`train/` and `valid/` at the beginning. Otherwise, it will throw out errors. Maybe considering adding `os.makedirs`
