### ISSUE TITLE
STrajNet Aggregator's and Path Decoder's Attention Layer Clarification

### ISSUE THREAD

**Issue by CeZh** [georgeliu233/OPGP#6]
Thanks for this amazing work! 
I have a few confusions with the notation when I read the paper and compare it with the code. Can you help me to solve it? Thanks a lot!

1. In the paper Figure 2 occupancy prediction part (shown below), it seems like you utilize the visual encoder's output as the key, and vector encoder's output as the query and value. However, in the code, the [`self.aggregator()`](https://github.com/georgeliu233/OPGP/blob/main/model/decoder.py#L87)'s "query" is the `bev_list` ,and its "key" and "value" are the `actor` features.
<img width="845" alt="image" src="https://github.com/user-attachments/assets/f354d6cd-22a7-43be-bfe4-2bd966a08544">

2. Similarly, also in Figure 2 path decoder part (shown below), the visual and vector multi-head attention layers "query" and "value" are the visual encoded features and vector encoded features, respectively. However, for the [code implementation](https://github.com/georgeliu233/OPGP/blob/main/model/decoder.py#L166), it seems like the `self_plan_query` is the actual "query". 
<img width="381" alt="image" src="https://github.com/user-attachments/assets/be170bd0-8d21-48f8-b2a9-3756f97eb6d5">

Can you help me to clarify these two confusions? Thank you so much!

**Comment by georgeliu233** [comment]
Hi, thanks for pointing this out and sorry for the misunderstanding! It is a typo in Figure 2, and should be Q /K, V instead.
